/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PropertyRegistry } from './PropertyRegistry.js';
export * as factories from './factories/index.js';
export { PropertyRegistry__factory } from './factories/PropertyRegistry__factory.js';