/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PropertyRegistry {
      
    export type PropertyStruct = {propertyAddress: string, owner: AddressLike, price: BigNumberish, exists: boolean}

    export type PropertyStructOutput = [propertyAddress: string, owner: string, price: bigint, exists: boolean] & {propertyAddress: string, owner: string, price: bigint, exists: boolean }
  
    }

  export interface PropertyRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getProperty" | "propertyCount" | "registerProperty" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PropertyRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getProperty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propertyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerProperty', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [propertyId: BigNumberish, previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [propertyId: bigint, previousOwner: string, newOwner: string];
      export interface OutputObject {propertyId: bigint, previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyRegisteredEvent {
      export type InputTuple = [propertyId: BigNumberish, owner: AddressLike, propertyAddress: string, price: BigNumberish];
      export type OutputTuple = [propertyId: bigint, owner: string, propertyAddress: string, price: bigint];
      export interface OutputObject {propertyId: bigint, owner: string, propertyAddress: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyRegistry;
    waitForDeployment(): Promise<this>;

    interface: PropertyRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProperty: TypedContractMethod<
      [_propertyId: BigNumberish, ],
      [PropertyRegistry.PropertyStructOutput],
      'view'
    >
    

    
    propertyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerProperty: TypedContractMethod<
      [_address: string, _price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [_propertyId: BigNumberish, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProperty'): TypedContractMethod<
      [_propertyId: BigNumberish, ],
      [PropertyRegistry.PropertyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'propertyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerProperty'): TypedContractMethod<
      [_address: string, _price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [_propertyId: BigNumberish, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PropertyRegistered'): TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(uint256,address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PropertyRegistered(uint256,address,string,uint256)': TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;
      PropertyRegistered: TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;
    
    };
  }